---
title: "temp"
author: "Stuart Miller"
date: "August 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

df <- read_csv('../data/train.csv')

df$LotFrontage[is.na(df$LotFrontage)] <- 0
df$Alley[is.na(df$Alley)] <- "None"
df$MasVnrType[is.na(df$MasVnrType)] <- "None"
df$MasVnrArea[is.na(df$MasVnrArea)] <- 0
df$BsmtQual[is.na(df$BsmtQual)] <- 0
df$BsmtCond[is.na(df$BsmtCond)] <- 0
df$BsmtExposure[is.na(df$BsmtExposure)] <- 0
df$BsmtFinType1[is.na(df$BsmtFinType1)] <- 0
df$BsmtFinType2[is.na(df$BsmtFinType2)] <- 0
df$Electrical[is.na(df$Electrical)] <- "SBrkr"
df$FireplaceQu[is.na(df$FireplaceQu)] <- "None"
df$GarageType[is.na(df$GarageType)] <- "None"
df$GarageYrBlt[is.na(df$GarageYrBlt)] <- mean(df$GarageYrBlt)
df$GarageFinish[is.na(df$GarageFinish)] <- "None"
df$GarageQual[is.na(df$GarageQual)] <- "None"
df$GarageCond[is.na(df$GarageCond)] <- "None"
df$PoolQC[is.na(df$PoolQC)] <- "None"
df$Fence[is.na(df$Fence)] <- "None"
df$MiscFeature[is.na(df$MiscFeature)] <- "None"

save.image(file = "../data/data.RData")
```

