---
title: "Ames Iowa Housing Prices (Analysis Two)"
author: "Paul Adams"
date: "August 3, 2019"
output: word_document
---

```{r, echo=T, message=F}
library(pacman)
p_load(tidyr,dplyr,purrr,stringr,ggplot2, MASS,DAAG, sjPlot, Hmisc)
```

```{r, echo=F}
setwd("C:/Users/Pablo/Desktop/DS 6371 - Statistical Foundations for Data Science/Kaggle Project")
df <- read.csv("train.csv", stringsAsFactors = F)
```

### Handle NAs
```{r, echo=T,warning=F, message=F}
# create dataframe for numeric data
dfTest.numeric <- dplyr::select_if(df, is.numeric) %>% data.frame()

# create dataframe for non-numeric data
dfTest.nonnumeric <- dplyr::select_if(df, is.factor) %>% data.frame()

#See structure for replacing NAs
str(df)

# UDF for flattening and ordering the correlation matrix
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

# Snapshot of all NAs
na_count <- sapply(df, function(cnt) sum(length(which(is.na(cnt)))))
na_count

########################################################################################################
#Start Area for handling NAs############################################################################
########################################################################################################

##############################################################################
#Start Checking Electrical NAs################################################
##############################################################################

# Which neighborhood is the NA for electrical in?
noElectric <- df[which(is.na(df$Electrical)),c("SalePrice","Neighborhood")]
noElectric

# Who services electricity in this neighborhoo?
timberElectric <- arrange(df[which(df$Neighborhood=="Timber"),c("SalePrice","Electrical")], SalePrice)
head(timberElectric)
tail(timberElectric)
# Timber looks to mostly use SBrkr so this should not be an issue to assume for the NA value for Electrical

##############################################################################
#End Checking Electrical NAs##################################################
##############################################################################

df$LotFrontage[is.na(df$LotFrontage)] <- 0
df$Alley[is.na(df$Alley)] <- "None" #@###########
df$MasVnrType[is.na(df$MasVnrType)] <- "None"
df$MasVnrArea[is.na(df$MasVnrArea)] <- 0
df$BsmtQual[is.na(df$BsmtQual)] <- 0
df$BsmtCond[is.na(df$BsmtCond)] <- 0
df$BsmtExposure[is.na(df$BsmtExposure)] <- 0
df$BsmtFinType1[is.na(df$BsmtFinType1)] <- 0
df$BsmtFinType2[is.na(df$BsmtFinType2)] <- 0
df$Electrical[is.na(df$Electrical)] <- "SBrkr"
df$FireplaceQu[is.na(df$FireplaceQu)] <- "None"
df$GarageType[is.na(df$GarageType)] <- "None"
df$GarageYrBlt[is.na(df$GarageYrBlt)] <- mean(df$GarageYrBlt)
df$GarageFinish[is.na(df$GarageFinish)] <- "None"
df$GarageQual[is.na(df$GarageQual)] <- "None"
df$GarageCond[is.na(df$GarageCond)] <- "None"
df$PoolQC[is.na(df$PoolQC)] <- "None"
df$Fence[is.na(df$Fence)] <- "None"
df$MiscFeature[is.na(df$MiscFeature)] <- "None"

########################################################################################################
#End Area for handling NAs##############################################################################
########################################################################################################
```

### Correlation matrix for quantitative values, forward, backward, both
```{r, echo=T,warning=F, message=F}
#See what variables are correlated with eachother, p-values
correlation.matrix <- rcorr(as.matrix(dfTest.numeric))
corDF <- data.frame(flattenCorrMatrix(correlation.matrix$r, correlation.matrix$P))

#Order the correlation matrix to show the highest correlated
data.frame(corDF[order(-corDF$cor),])
quantDataModel <- corDF[which(corDF$cor >= 0.5),]

fitQuant <- lm(SalePrice ~ OverallQual + YearBuilt + YearRemodAdd + TotalBsmtSF + X1stFlrSF + GrLivArea + FullBath + TotRmsAbvGrd + GarageCars + GarageArea, data = df)

# Model using all variables
fitFull <- lm(SalePrice ~ Id + MSSubClass + MSZoning + LotFrontage + LotArea + Street + Alley + LotShape + LandContour + Utilities + LotConfig + LandSlope + Neighborhood + Condition1 + Condition2 + BldgType + HouseStyle + OverallQual + OverallCond + YearBuilt + YearRemodAdd + RoofStyle + RoofMatl + Exterior1st + Exterior2nd + MasVnrType + MasVnrArea + ExterQual + ExterCond + Foundation + BsmtQual + BsmtCond + BsmtExposure + BsmtFinType1 + BsmtFinSF1 + BsmtFinType2 + BsmtFinSF2 + BsmtUnfSF + TotalBsmtSF + Heating + HeatingQC + CentralAir + Electrical + X1stFlrSF + X2ndFlrSF + LowQualFinSF + GrLivArea + BsmtFullBath + BsmtHalfBath + FullBath + HalfBath + BedroomAbvGr + KitchenAbvGr + KitchenQual + TotRmsAbvGrd + Functional + Fireplaces + FireplaceQu + GarageType + GarageYrBlt + GarageFinish + GarageCars + GarageArea + GarageQual + GarageCond + PavedDrive + WoodDeckSF + OpenPorchSF + EnclosedPorch + X3SsnPorch + ScreenPorch + PoolArea + PoolQC + Fence + MiscFeature + MiscVal + MoSold + YrSold + SaleType + SaleCondition, data = df)
?stepAIC
# Forward Selection
stepForward.model <- stepAIC(fitQuant, direction = "forward", trace = F)
summary(stepForward.model)
stepForward.model$anova

# Backwise Selection
stepBackward.model <- stepAIC(fitQuant, direction = "backward", trace = F)
summary(stepBackward.model)
stepBackward.model$anova

# Stepwise Selection
stepBoth.model <- stepAIC(fitQuant, direction = "both", trace = F)
summary(stepBoth.model)
stepBoth.model$anova
```